### ISSUE TITLE
not working anymore

### ISSUE THREAD

**Issue by Mavrikant** [Hexalyse/Interpals-Autovisit#1]
They changed form values. I tried new values but it didnt work. Can you look at it again.

**Comment by 0xBRM** [comment]
I believe the problem is that the payload needs to include the csrf-token. The script needs to parse the page to get the unique token and send 'csrf-token' in the payload.

... and of course you would be Turkish.

**Comment by ghost** [comment]
I tried to fix it by myself but no luck, it just doesn't log in.

**Comment by cdrage** [comment]
@Mavrikant @CrisBRM @alveola666 
I've forked and cleaned up the script a teeny bit (I'll work on it a bit more later).

Repo: https://github.com/cdrage/interpals

I added the whole csrf-token request as per @CrisBRM however, ironically, the interpals site went down as soon as I began testing it. So I haven't received a significant amount of views yet so I know it's working.

Feel free to check it out / star it / open up an issue if it's not working, I'm pretty active on github so just ping me whenever.

**Comment by 0xBRM** [comment]
@cdrage I fixed it a while back but forgot to post here. Yours is a bit cleaner so I'll test it soon. Looks correct, however.

Revision: to make it compatible with Python 3, you need to use print as a function.
Revision2: python 3 renamed raw_input to input.

**Comment by cdrage** [comment]
@CrisBRM mind sharing the script you used so I can check it against my code / headers?

**Comment by 0xBRM** [comment]
@cdrage I have long since deleted it oops.

**Comment by cdrage** [comment]
@CrisBRM do you remember what token name you happened to use within the requests header? Trying to get this to work still. I'm using:

```

            headers = {'X-CSRF-Token': csrf_token, 'Referer': URL}
```

**Comment by interpale** [comment]
my pyhton files are closing as soon as i open it.how can i fix it??
and i am still curious about if you can find any substitute or not?

**Comment by anonimousse12345** [comment]
@cdrage csrf token has to be in the login POST params only

I also made a different version:
https://github.com/anonimousse12345/qtcreeper

**Comment by Hexalyse** [comment]
Sorry for not seeing this issue before. I was busy and didn't have time/will to fix bugs on my github repositories back then. Moreover, I didn't think anybody would be using this very old script anymore ! Well, I guess Interpals is not dead yet... I thought this website became obsolete since long.

@anonimousse12345 Your script seems way more elaborate, I'll definitely look through it and maybe give it a try.

**Comment by anonimousse12345** [comment]
@Hexalyse interpals, obsolete? Now I'm curious what better alternative there is... ;)

**Comment by Hexalyse** [comment]
@anonimousse12345 It seems there aren't any. Or at least, I never found better alternatives.
Which is sad, because it means penpals websites are kind of dead now.
